henswedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^filer/', include('filer.urls')),
    url(r'^dishes/', include('wedding_food.urls')),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wedding_food/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import PromiseDish, ConfirmPromise, DishDetailView

urlpatterns = [
    url(r'^promise/', PromiseDish.as_view(), name="promise-dish"),
    url(r'^confirm-promise/', ConfirmPromise.as_view(), name="confirm-promise"),
    url(r'^(?P<pk>\d+)/$', DishDetailView.as_view(), name="dish-detail"),
    # url(r'^update-promise/(?P<pk>\d+)/$', UpdatePromise.as_view(), name='update-promise')
    
]

wedding_food/models.py
from __future__ import unicode_literals

from django.db import models
from filer.fields.image import FilerImageField
from filer.fields.file import FilerFileField
from django.utils.six import python_2_unicode_compatible
from djangocms_text_ckeditor.fields import HTMLField
from django.core.urlresolvers import reverse


# Create your models here.

@python_2_unicode_compatible
class Dish(models.Model):

	title = models.CharField(max_length=128, blank=True, default='')
	description = HTMLField(default='', blank=True)

	ingredients = models.TextField(default='', blank=True)
	method = models.TextField(default='', blank=True)

	link = models.URLField(null=True, blank=True)
	image = FilerImageField(
		null=True, blank=True, related_name="dish_picture"
	)

	difficulty = models.PositiveIntegerField(default=2)
	num_required = models.PositiveIntegerField(default=1)
	serves = models.PositiveIntegerField(default=2)

	def get_absolute_url(self):
		return reverse(
			'dish-detail',
			kwargs= {
				'pk':self.pk
			}
		)

	def total_promised(self):
		return "{} / {}".format(self.promise_set.count(), self.num_required)

	def portions_promised(self):
		return self.serves * self.promise_set.count()

	@property
	def available(self):
		return max(0, self.num_required - self.promise_set.count())

	def remaining(self):
		return [""] * self.available

	def __str__(self):
		return self.title

@python_2_unicode_compatible
class Promise(models.Model):
	name = models.CharField(max_length=128, null=True, blank=True)
	dish = models.ForeignKey(Dish)
	email = models.EmailField(null=True, blank=True)

	def __str__(self):
		return self.name or self.dish.title or 'Promise {}'.format(self.pk)

wedding_food/views.py
from django.shortcuts import render
from django.views.generic import View, FormView, CreateView, UpdateView, DetailView

from django import forms
from .models import Dish, Promise
# Create your views here.
from django_ajax.mixin import AJAXMixin
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage, send_mail
from django.template.loader import get_template


class PromiseForm(forms.Form):
    dish = forms.ModelChoiceField(queryset=Dish.objects.all())



class PromiseDetailForm(forms.ModelForm):
    dish = forms.ModelChoiceField(
        queryset=Dish.objects.all(),
        widget=forms.HiddenInput()
    )

    name = forms.CharField(label="Your name", required=False)
    email = forms.EmailField(label="Your Email", required=False)

    quantity = forms.IntegerField(label="I'll bring this many lots of this recipe", required=True, initial=1)

    class Meta:
        model = Promise
        fields = '__all__'
    

class PromiseDish(AJAXMixin, FormView):
    form_class = PromiseForm
    template_name = 'home.html'

    def form_invalid(self, form):
        return {'error':form.errors}

    def form_valid(self, form):

        dish = form.cleaned_data['dish']

        return {
            'count' : dish.available,
            "dish_name": dish.title,
            "confirm_url": reverse('confirm-promise')
        }

class ConfirmPromise(AJAXMixin, FormView):
    form_class = PromiseDetailForm
    template_name = 'home.html'

    def form_invalid(self, form):
        return form.errors

    def form_valid(self, form):

        quantity = form.cleaned_data.get('quantity')

        dish = form.cleaned_data.get('dish')

        quantity = max(1, min(dish.available, quantity))

        promises = []

        for i in range(quantity):
            promise = Promise(
                    email=form.cleaned_data.get('email'),
                    name=form.cleaned_data.get('name'),
                    dish=form.cleaned_data.get('dish')
            )
            promises.append(promise)
        Promise.objects.bulk_create(promises)

        if bool(form.cleaned_data['email']):
            subject = "[Ben&Jo's Wedding] Thanks for volunteering to cook!"
            t = get_template('food/thankyou-email.txt')
            c = {'promise': promise, 'quantity': quantity}
            message = t.render(c)
            from_email = 'Ben & Jo <blrharling@gmail.com>'
            to_email = [promise.email]

            email = EmailMessage(
                subject=subject,
                body=message,
                from_email=from_email,
                to=to_email,
                bcc=['blrharling@gmail.com', 'joannacc@hotmail.co.uk']
            )
            email.send()

        dish.refresh_from_db()
        return {
            "dish": dish.pk,
            "available": dish.available
        }

class DishDetailView(DetailView):
    model = Dish

    def get_context_data(self, **kwargs):
        context = super(DishDetailView, self).get_context_data()
        context['promise_form'] = PromiseDetailForm()
        return context

wedding_food/templates/food/food-plugin.html
{% load thumbnail static cms_tags sekizai_tags bootstrap3 %}
{% for dish in dishes %}
	<div class="row">
	{% render_model_block dish %}
		<div class="dish clearfix">
			<div class="col-sm-4">
				<div class="food-image" style="background-image:url({% thumbnail dish.image 400x400 upscale crop %});"></div>
				<!--<img src="{% thumbnail dish.image 400x400 upscale crop %}" class="img-responsive">-->
			</div>
			<div class="col-sm-6">
				<h3>{{dish.title}}</h3>
				<p>{{dish.description|truncatewords_html:40}}</p>
				<a class="btn btn-success" href="{{dish.get_absolute_url}}">
					View / Make recipe
				</a>
				{% comment %}
				{% if dish.available %}
					<a class="btn btn-success promise-button" href="#" data-dish="{{dish.pk}}">
						I'll Make this <span class="glyphicon gliphicon-check"></span>
					</a>
				{% else %}
					<p>We've got enough of these promised already!</p>
				{% endif %}

				

				<div>
				{% for promise in dish.promise_set.all %}
					<span class="promise promised">✓</span>
				{% endfor %}

				{% for item in dish.remaining %}
					<a href="#" class="promise needed" data-dish="{{dish.pk}}">o</a>
				{% endfor %}
				</div>

				{% endcomment %}

			</div>

			{% if dish.available %}
				<span class="promises" data-dish="{{ dish.pk }}">
					<small>We need</small>
					<strong>{{dish.available}}</strong>
					<small>more of these</small>
				</span>
			{% endif %}



		</div>
		
		{% endrender_model_block %}
	</div>
{% endfor %}

{% addtoblock "modals" %}
<!-- Modal -->
<div class="modal fade-scale" id="complete-promise" tabindex="-1" role="dialog" aria-labelledby="complete-promiseLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
<!--       <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="complete-promiseLabel">Thank You! {% bootstrap_icon "heart" %}</h4>
      </div> -->
      <div class="modal-body">
       	<div>
       		<h3>Thanks for volunteering to cook!</h3>
       		<h4>You've chosen <span class="dish-name"></span></h4>
       		<p>We're really grateful for your help. Please enter your name and email address below so that we can send you the recipe. If you'd like to double or even triple-up the recipe, please enter a quantity below ( please enter how many times you can cook the whole dish rather than servings ). {% bootstrap_icon "heart" %}</strong></p>
       		<br>
       		<strong>Thankyou!</strong> Looking forward to seeing you at the end of July!
       		<br>
       		<br>
       	</div>
        <form action="" method="post" class="form" id="update-promise-form">
{#         	<p>Yes, please send me an email with the recipe details.<br><br></p> #}
        	{% csrf_token %}
        	{% bootstrap_form promise_form %}
        	{% buttons %}
        		<button type="submit" name="with-email" id="confirm-with-email" class="btn btn-success">
		            {% bootstrap_icon "star" %} Confirm and send me a reminder email
		        </button>
		        <button type="button" class="btn btn-warning" data-dismiss="modal">I've changed my mind &times;</button>
        	{% endbuttons %}
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>


{% endaddtoblock %}

{% addtoblock "js" %}
	<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
{% endaddtoblock %}

{% addtoblock "js" %}
	<script type="text/javascript">
	$(document).ready(function() {

		$('#update-promise-form').on('submit', function (e) {
			var data = {
				"name": $('input#id_name').val(),
				"email": $('input#id_email').val(),
				"dish": $('input#id_dish').val(),
				"quantity": $('input#id_quantity').val()
			}

			url = $('#update-promise-form').attr('action');

			ajaxPost(
				url,
				data,
				function (data) {

					$('#complete-promise').modal('hide');
					$('.promises[data-dish="' + data.dish + '"]')
						.addClass('active')
						.find('strong')
						.text(data.available);
				}
			)

			return false;
		});

		$('#confirm-no-email').on('click', function (e) {
			$('input#id_name, input#id_email').removeAttr('required');
			return true;
		});

		$('#confirm-with-email').on('click', function(e) {
			$('input#id_name, input#id_email').attr('required', 'required');
			return true;
		});

		$('.promise-button, .promise.needed').on('click', function (e) {
			var dish_id = $(e.target).data('dish');

			$('#id_dish').val(dish_id);

			ajaxPost(
				'{% url 'promise-dish' %}', 
				{
					'dish':dish_id
				},
				function (data) {
					$('.promises[data-dish="' + dish_id + '"]')
						.addClass('active')
						.find('strong')
						.text(data.count);

					$('#update-promise-form').attr('action', data.confirm_url);
					$('.dish-name').text(data.dish_name);
					$('input#id_dish').val(dish_id);
				}
			);

			$('#complete-promise').modal('toggle');
			return false;
		})

	});
	</script>
{% endaddtoblock %}

wedding_food/templates/wedding_food/dish_detail.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags bootstrap3 static thumbnail %}

{% block page_head %}
	
{% endblock page_head %}

{% block content %}
	<div class="container">
		<div class="row">
			{% render_model_block dish %}
			<div class="col-md-10 col-md-offset-1">
				<h2>{{object.title}}</h2>

				<div class="row">
					<div class="col-sm-6">
						<img class="img-responsive" src="{% thumbnail dish.image 500x350 upscale crop %}">
					</div>

					<div class="col-sm-6">
						<table class="table">
							<tr>
								<td>Serves</td>
								<td>{{dish.serves}}</td>
							</tr>

							<tr>
								<td>We need</td>
								<td>{{dish.available}}</td>
							</tr>
							<tr>
								<td>From</td>
								<td><a href="{{dish.link}}">{{dish.link}}</a></td>
							</tr>



								

						</table>

						{% if dish.available or dish.num_required == 0 %}
							<a class="btn btn-success promise-button" href="#" data-dish="{{dish.pk}}">
								I'll Make this <span class="glyphicon gliphicon-check"></span>
							</a>
						{% else %}
							We've got enough of these promised already!
						{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
					<hr>
						
						<p>
							{{dish.description|safe}}
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-6">
						<h3>Ingredients</h3>
						{{dish.ingredients|linebreaks}}
					</div>
					<div class="col-sm-6">
						<h3>Method</h3>
						{{dish.method|linebreaks}}
					</div>
				</div>

			</div>
		</div>

		{% endrender_model_block %}

		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				{% if dish.available or dish.num_required == 0 %}
					<a class="btn btn-success promise-button" href="#" data-dish="{{dish.pk}}">
						I'll Make this <span class="glyphicon gliphicon-check"></span>
					</a>
				{% else %}
					<p>We've got enough of these promised already!</p>
				{% endif %}
			</div>
		</div>
	</div>




	{% addtoblock "modals" %}
<!-- Modal -->
<div class="modal fade-scale" id="complete-promise" tabindex="-1" role="dialog" aria-labelledby="complete-promiseLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
<!--       <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="complete-promiseLabel">Thank You! {% bootstrap_icon "heart" %}</h4>
      </div> -->
      <div class="modal-body">
       	<div>
       		<h3>Thanks for volunteering to cook!</h3>
       		<h4>You've chosen <span class="dish-name"></span></h4>
       		<p>We're really grateful for your help. Please enter your name and email address below so that we can send you the recipe. If you'd like to double or even triple-up the recipe, please enter a quantity below ( please enter how many times you can cook the whole dish rather than servings ). {% bootstrap_icon "heart" %}</strong></p>
       		<br>
       		<strong>Thankyou!</strong> Looking forward to seeing you at the end of July!
       		<br>
       		<br>
       	</div>
        <form action="" method="post" class="form" id="update-promise-form">
{#         	<p>Yes, please send me an email with the recipe details.<br><br></p> #}
        	{% csrf_token %}
        	{% bootstrap_form promise_form %}
        	{% buttons %}
        		<button type="submit" name="with-email" id="confirm-with-email" class="btn btn-success">
		            {% bootstrap_icon "star" %} Confirm and send me a reminder email
		        </button>
		        <button type="button" class="btn btn-warning" data-dismiss="modal">I've changed my mind &times;</button>
        	{% endbuttons %}
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>
{% endaddtoblock %}

{% addtoblock 'modals' %}
<div class="modal fade-scale" id="promise-thanks" tabindex="-1" role="dialog" aria-labelledby="complete-promiseLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
		<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="complete-promiseLabel">Thank You! {% bootstrap_icon "heart" %}</h4>
      	</div>
      <div class="modal-body">
       	<div>
       	 	<p>Just emailing you the details ... bear with us a second</p>
       	</div>
      </div>
    </div>
  </div>
</div>

{% endaddtoblock %}

{% addtoblock "js" %}
	<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
{% endaddtoblock %}

{% addtoblock "js" %}
	<script type="text/javascript">
	$(document).ready(function() {

		$('#update-promise-form').on('submit', function (e) {
			var data = {
				"name": $('input#id_name').val(),
				"email": $('input#id_email').val(),
				"dish": $('input#id_dish').val(),
				"quantity": $('input#id_quantity').val()
			}

			url = $('#update-promise-form').attr('action');



			ajaxPost(
				url,
				data,
				function (data) {

					$('#complete-promise').modal('hide');
					$('#promise-thanks').modal('hide');
					$('.promises[data-dish="' + data.dish + '"]')
						.addClass('active')
						.find('strong')
						.text(data.available);
				},
				{
					onBeforeSend: function () {
						$('#complete-promise').modal('hide');
						$('#promise-thanks').modal('show');
					}
				}
			)

			return false;
		});

		$('#confirm-no-email').on('click', function (e) {
			$('input#id_name, input#id_email').removeAttr('required');
			return true;
		});

		$('#confirm-with-email').on('click', function(e) {
			$('input#id_name, input#id_email').attr('required', 'required');
			return true;
		});

		$('.promise-button, .promise.needed').on('click', function (e) {
			var dish_id = $(e.target).data('dish');

			$('#id_dish').val(dish_id);

			ajaxPost(
				'{% url 'promise-dish' %}', 
				{
					'dish':dish_id
				},
				function (data) {
					$('.promises[data-dish="' + dish_id + '"]')
						.addClass('active')
						.find('strong')
						.text(data.count);

					$('#update-promise-form').attr('action', data.confirm_url);
					$('.dish-name').text(data.dish_name);
					$('input#id_dish').val(dish_id);
				}
			);

			$('#complete-promise').modal('toggle');
			return false;
		})

	});
	</script>
{% endaddtoblock %}


{% endblock content %}